language: python
python:
  - "3.6"

install:
  - python3.6 -m pip install flake8
  - cd backend
  - python3.6 -m pip install -t vendored -r requirements.txt
  - cd ..

script:
  - pwd
  - python3.6 -m flake8 -v backend/*.py --max-line-length=130
