service: infinimonkey

custom:
  credentialsProfile: heap
  region: eu-west-1
  ramblingsTableName: ${self:service}-ramblings
  corpusBucketName: ${self:service}-corpus

provider:
  name: aws
  runtime: python3.6
  region: ${self:custom.region}
  profile: ${self:custom.credentialsProfile}
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:BatchWriteItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:Scan
        - dynamodb:GetItem
      Resource: "arn:aws:dynamodb:${self:custom.region}:*:table/${self:custom.ramblingsTableName}"
    - Effect: Allow
      Action:
        - s3:ListBucket
        - s3:GetObject
      Resource:
        - "arn:aws:s3:::${self:custom.corpusBucketName}"
        - "arn:aws:s3:::${self:custom.corpusBucketName}/*"
  environment:
    RAMBLINGS_TABLE_NAME: ${self:custom.ramblingsTableName}
    CORPUS_BUCKET_NAME: ${self:custom.corpusBucketName}

functions:
  rambler:
    handler: rambler.handler
    memorySize: 512
    events:
      - schedule: rate(12 hours)
  apiGetRamblings:
    handler: ramblings-api.get_ramblings
    memorySize: 256
    events:
      - http:
          path: ramblings
          method: get
          cors: true

package:
  exclude:
    - "*.txt"
    - "*.md"
    - "*.yml"
    - "*.json"

resources:
  Resources:

    RamblingsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:custom.ramblingsTableName}
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1

    CorpusBucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: ${self:custom.corpusBucketName}
