service: infinimonkey

custom:
  credentialsProfile: heap
  region: eu-west-1
  tableName: infinimonkey

provider:
  name: aws
  runtime: python3.6
  region: ${self:custom.region}
  profile: ${self:custom.credentialsProfile}
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:BatchWriteItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:Scan
        - dynamodb:GetItem
      Resource: "arn:aws:dynamodb:${self:custom.region}:*:*"
  environment:
    TABLE_NAME: ${self:custom.tableName}

functions:
  apiGetItems:
    handler: api.get_items
    memorySize: 256
    events:
      - http:
          path: items
          method: get
          cors: true

package:
  exclude:
    - "*.txt"
    - "*.md"
    - "*.yml"
    - "*.json"

resources:
  Resources:

    AphorismTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:custom.tableName}
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1

    CorpusBucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: ${self:service}
